# Generated by Django 3.1.7 on 2021-03-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('CompanyName', models.CharField(blank=True, max_length=200, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('JobTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('JobDescription', models.TextField(blank=True, null=True)),
                ('JobLocation', models.CharField(blank=True, max_length=200, null=True)),
                ('IsActive', models.BooleanField(verbose_name=True)),
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('JobType', models.CharField(blank=True, max_length=200, null=True)),
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('SkillSetName', models.CharField(blank=True, max_length=200, null=True)),
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostSkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillLevel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('JobPostID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.jobpost')),
                ('SkillSetID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.skillset')),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='JobTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.jobtype'),
        ),
    ]
