# Generated by Django 3.1.7 on 2021-04-17 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210414_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.CharField(blank=True, max_length=255, null=True)),
                ('skill', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(blank=True, max_length=255, null=True)),
                ('r_email', models.CharField(blank=True, max_length=255, null=True)),
                ('r_password', models.CharField(blank=True, max_length=255, null=True)),
                ('r_account_status', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='account_status',
            new_name='a_account_status',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='file_upload',
            new_name='a_file_upload',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='gender',
            new_name='a_gender',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='company_id',
        ),
        migrations.AddField(
            model_name='applicant',
            name='a_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='a_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='a_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='Recruiter_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_apply_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='applicant',
            name='a_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.applicant_profile'),
        ),
    ]
