# Generated by Django 3.1.7 on 2021-04-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210417_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_type',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_apply_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
