# Generated by Django 3.1.7 on 2021-04-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210417_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
