# Generated by Django 3.1.7 on 2021-04-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210417_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_apply_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
