# Generated by Django 3.1.7 on 2021-04-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210417_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='Recruiter_ID',
            new_name='Recruiter',
        ),
    ]
