# Generated by Django 3.1.7 on 2021-05-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210422_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='a_profile',
        ),
        migrations.AddField(
            model_name='applicant_profile',
            name='applicant_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.applicant'),
        ),
    ]
