# Generated by Django 3.1.7 on 2021-05-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210503_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='a_gender',
        ),
    ]
