# Generated by Django 3.1.7 on 2021-05-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_applicant_a_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='a_account_status',
            new_name='account_status',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='a_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='a_file_upload',
            new_name='file_upload',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='a_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='a_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='r_account_status',
            new_name='account_status',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='r_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='r_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='r_password',
            new_name='password',
        ),
    ]
