# Generated by Django 3.1.7 on 2021-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210505_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
