# Generated by Django 3.1.7 on 2021-05-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20210507_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='last_login',
        ),
    ]
