# Generated by Django 3.1.7 on 2021-05-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_applicant_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant_profile',
            name='applicant_ID',
        ),
        migrations.RemoveField(
            model_name='applicationdetail',
            name='applicant_id',
        ),
        migrations.RemoveField(
            model_name='applicationdetail',
            name='job_post_id',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Applicant_Profile',
        ),
        migrations.DeleteModel(
            name='ApplicationDetail',
        ),
    ]
