# Generated by Django 3.1.7 on 2021-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_profile_curriculum_vitae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
