# Generated by Django 3.1.7 on 2021-05-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20210512_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
