# Generated by Django 3.1.7 on 2021-05-29 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_jobpost_flag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
