# Generated by Django 3.1.7 on 2021-06-05 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20210605_1022'),
        ('pages', '0025_auto_20210605_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='Recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.employers'),
        ),
    ]
