# Generated by Django 3.1.7 on 2021-06-05 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20210605_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='Employers',
        ),
    ]
