# Generated by Django 3.1.7 on 2021-06-05 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_employer'),
        ('pages', '0028_remove_jobpost_employers'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='Employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.employer'),
        ),
    ]
