# Generated by Django 3.1.7 on 2021-06-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_jobpost_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
