# Generated by Django 3.1.7 on 2021-06-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_employer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_size', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
    ]
