# Generated by Django 3.1.7 on 2021-06-05 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_remove_jobpost_employers'),
        ('employer', '0004_auto_20210605_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employers',
        ),
    ]
