# Generated by Django 3.1.7 on 2021-06-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_employer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('job_title', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_summary', models.TextField(blank=True, null=True)),
                ('job_time', models.DateField(blank=True, null=True)),
                ('job_apply_url', models.TextField(blank=True, null=True)),
                ('job_salary', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('company_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(verbose_name=True)),
                ('Employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.employer')),
            ],
        ),
    ]
