# Generated by Django 3.1.7 on 2021-06-08 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0010_auto_20210607_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(verbose_name=True)),
                ('Applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.employer')),
            ],
        ),
    ]
