# Generated by Django 3.1.7 on 2021-07-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_auto_20210619_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='Employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.employer'),
        ),
    ]
