# Generated by Django 3.1.7 on 2021-05-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='curriculum_vitae',
            new_name='CV',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='graduate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='other',
        ),
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tag_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
